### POST JOIN
POST http://localhost:7777/api/v1/auth/join
Content-Type: application/json

{
  "user_id": "tony",
  "password": "stark",
  "nickname": "iron-man"

}
###

### POST LOGIN
POST http://localhost:7777/api/v1/auth/login
Content-Type: application/json

{
  "user_id": "tony",
  "password": "stark"
}
###


### POST PETER JOIN
POST http://localhost:7777/api/v1/auth/join
Content-Type: application/json

{
  "user_id": "peter",
  "password": "parker",
  "nickname": "spider-man"

}
###

### POST PETER LOGIN
POST http://localhost:7777/api/v1/auth/login
Content-Type: application/json

{
  "user_id": "peter",
  "password": "parker"
}
###

### POST USER1 JOIN
POST http://localhost:7777/api/v1/auth/join
Content-Type: application/json

{
  "user_id": "user1",
  "password": "1234",
  "nickname": "user1"

}
###

### POST USER1 LOGIN
POST http://localhost:7777/api/v1/auth/login
Content-Type: application/json

{
  "user_id": "user1",
  "password": "1234"
}
###

### POST USER2 JOIN
POST http://localhost:7777/api/v1/auth/join
Content-Type: application/json

{
  "user_id": "user2",
  "password": "1234",
  "nickname": "user2"

}
###

### POST USER1 LOGIN
POST http://localhost:7777/api/v1/auth/login
Content-Type: application/json

{
  "user_id": "user2",
  "password": "1234"
}

### POST USER3 JOIN
POST http://localhost:7777/api/v1/auth/join
Content-Type: application/json

{
  "user_id": "user3",
  "password": "1234",
  "nickname": "user3"

}
###

### POST USER3 LOGIN
POST http://localhost:7777/api/v1/auth/login
Content-Type: application/json

{
  "user_id": "user3",
  "password": "1234"
}
###

### POST USER4 JOIN
POST http://localhost:7777/api/v1/auth/join
Content-Type: application/json

{
  "user_id": "user4",
  "password": "1234",
  "nickname": "user4"

}
###

### POST USER4 LOGIN
POST http://localhost:7777/api/v1/auth/login
Content-Type: application/json

{
  "user_id": "user4",
  "password": "1234"
}
###

