### POST ADD NEW CART
POST http://localhost:7777/api/v1/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoidG9ueSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzkyNzgzNjMsImV4cCI6MTc0OTI3ODM2M30.XyWaO9A9xR3cfLivz9QHD8_AHH3uQmOsyIm-jgnwupQ


{
  "product_id": "1",
  "size": "free"
}
###

### POST ADD NEW CART MORE
POST http://localhost:7777/api/v1/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoidG9ueSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzkyNzgzNjMsImV4cCI6MTc0OTI3ODM2M30.XyWaO9A9xR3cfLivz9QHD8_AHH3uQmOsyIm-jgnwupQ


{
  "product_id": "2",
  "size": "free"
}
###



