### POST CREATE NEW SETTLEMENT
POST http://localhost:7777/settlement/api/v1/settlement/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoidG9ueSIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzQxMjgwMzg1fQ.DCU8pWnUiYkwXD-pE4cvmmH9VH_s2B0YGL9gcVFYgF8

{
  "settlement_name": "강릉여행"
}

### POST JOIN NEW SETTLEMENT TO MEMEBER
POST http://localhost:7777/settlement/api/v1/settlement/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoidG9ueSIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzQxMjgwMzg1fQ.DCU8pWnUiYkwXD-pE4cvmmH9VH_s2B0YGL9gcVFYgF8

{
  "settlement_id": 1
}

